// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMGsovfkBjhDYldFIWV4UovSdExfv3x-c',
    appId: '1:880167273080:web:5c95c456a6bac4052e238d',
    messagingSenderId: '880167273080',
    projectId: 'video-share-ay',
    authDomain: 'video-share-ay.firebaseapp.com',
    databaseURL: 'https://video-share-ay-default-rtdb.firebaseio.com',
    storageBucket: 'video-share-ay.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEG5f_2sdO2hBKwgE5M8tE20E87yahKaE',
    appId: '1:880167273080:android:b617b2484a0b98462e238d',
    messagingSenderId: '880167273080',
    projectId: 'video-share-ay',
    databaseURL: 'https://video-share-ay-default-rtdb.firebaseio.com',
    storageBucket: 'video-share-ay.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhSyF3Oim6o9w-89Fwcn_lO0yo58xXCpE',
    appId: '1:880167273080:ios:5a385919e95dc75f2e238d',
    messagingSenderId: '880167273080',
    projectId: 'video-share-ay',
    databaseURL: 'https://video-share-ay-default-rtdb.firebaseio.com',
    storageBucket: 'video-share-ay.appspot.com',
    iosBundleId: 'com.example.videoShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhSyF3Oim6o9w-89Fwcn_lO0yo58xXCpE',
    appId: '1:880167273080:ios:c19c843b25fb43982e238d',
    messagingSenderId: '880167273080',
    projectId: 'video-share-ay',
    databaseURL: 'https://video-share-ay-default-rtdb.firebaseio.com',
    storageBucket: 'video-share-ay.appspot.com',
    iosBundleId: 'com.example.videoShare.RunnerTests',
  );
}
